# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e730178810751545298b0de3511d05cf8ee6bf0180fc6507cb6f04ab07dce4ddc3fc121e55e6faa8717d276c8f4b489481e1828257fe4884adcf3f5f7b193c

test:
  secret_key_base: 98e0e787190b26c2eb8e5fe179b74cb53c9d42726b0d82e82d189fd081535ca441522d3d8b56601ef56af7a388c769c011e4906b1a00559d9d1a6431ab7a34d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
